### ISSUE TITLE
qnlp-experiment.jpynb: import error

### ISSUE THREAD

**Issue by dtchang** [discopy/discopy#141]
ImportError: cannot import name 'Ty' from 'discopy'

**Comment by toumix** [comment]
The qnlp-experiment notebook was implemented with DisCoPy v0.5 so you can try `pip install discopy==0.5` instead.

**Comment by dtchang** [comment]
It works with v0.5. Since it is now part of v1.0, please update it to work with v1.0.

v1.0 breaks v0.5 and there is no migration guide, which is quite bad.

**Comment by toumix** [comment]
You're right we should have made a choice, either update the notebook or get rid of it.

I think we are going for the second option: this notebook was meant as an archive of our first experiment so it does not make sense to re-run it again, and it has now become redundant with the [QNLP tutorial](https://docs.discopy.org/en/main/notebooks/qnlp.html) which contains almost the same material with better explanations.

As for the migration guide, the best we have at the moment is the description of the [v1.0 release](https://github.com/discopy/discopy/releases/tag/0.1.0). I believe your issue would be solved by replacing `from discopy import` by `from discopy.grammar.pregroup import`.

Let me know if you have other issues.

**Comment by dtchang** [comment]
Removing the notebook is a good solution, for the reasons you've stated. QNLP Tutorial is better.

The release note, unfortunately, doesn't help as a migration guide. For example, for
_from discopy import Ty, Word_
it is not clear how it should be updated to. In v1.0, there are so many different Ty and Word, residing in separate and different packages. The same is true for many other classes. I tried to update the Lorentz code without success, and the Lorentz team has no interest to update it to v1.0. 

So, I'm forced to stay with v0.5.

BTW, thank you and your team for DisCoPy and many excellent associated publications.
